export const DummyMenu = [
    {
        id: '1',
        title: 'Pancakes',
        price: 12.00,
        description: 'Fluffy pancakes served with maple syrup and fresh berries.',
        category: 'Breakfast',
        image: require('./Images/Menu/Breakfast/Pancakes.jpg'),
    },
    {
        id: '2',
        title: 'Avocado Toast',
        price: 14.00,
        description: 'Smashed avocado on sourdough, topped with poached eggs and chili flakes. ',
        category: 'Breakfast',
        image: require('./Images/Menu/Breakfast/Avocado-Toast.jpg'),
    },
    {
        id: '3',
        title: 'French Toast',
        price: 13.00,
        description: 'Thick-cut brioche soaked in cinnamon-vanilla batter, served with whipped cream and berries.',
        category: 'Breakfast',
        image: require('./Images/Menu/Breakfast/French-Toast.jpg'),
    },
    {
        id: '4',
        title: 'Full English Breakfast',
        price: 18.00,
        description: 'Freshly cooked eggs, bacon, sausage, baked beans, grilled tomatoes, and toast.',
        category: 'Breakfast',
        image: require('./Images/Menu/Breakfast/Full-English.jpg'),
    },
    {
        id: '5',
        title: 'Acai Bowl',
        price: 12.00,
        description: 'Acai purée topped with banana, granola, coconut flakes, and honey.',
        category: 'Breakfast',
        image: require('./Images/Menu/Breakfast/Acai.jpg'),
    },
    {
        id: '6',
        title: 'BLT',
        price: 13.00,
        description: 'Crispy bacon, fresh lettuce, and ripe tomatoes on toasted sourdough bread, slathered with Aioli.',
        category: 'Breakfast',
        image: require('./Images/Menu/Breakfast/BLT.jpg'),
    },
    {
        id: '7',
        title: 'Caesar Salad',
        price: 14.00,
        description: 'Romaine lettuce, parmesan, croutons, and Caesar dressing, with grilled chicken. ',
        category: 'Lunch',
        image: require('./Images/Menu/Lunch/Caesar-Salad.jpg'),
    },
    {
        id: '8',
        title: 'Grilled Chicken Sandwich',
        price: 16.00,
        description: 'Grilled chicken breast, lettuce, tomato, avocado, and chipotle mayo on a ciabatta roll.',
        category: 'Lunch',
        image: require('./Images/Menu/Lunch/Grilled-Chicken-Sandwich.jpg'),
    },
    {
        id: '9',
        title: 'Club Sandwich',
        price: 15.00,
        description: 'Turkey, bacon, lettuce, tomato, and mayo layered on toasted bread.',
        category: 'Lunch',
        image: require('./Images/Menu/Lunch/Club-Sandwich.jpg'),

    },
    {
        id: '10',
        title: 'Spaghetti Bolognese',
        price: 18.00,
        description: 'House-made spaghetti pasta with rich bolognese sauce and freshly grated parmesan. ',
        category: 'Lunch',
        image: require('./Images/Menu/Lunch/Spaghetti-Bolognese.jpg'),

    },
    {
        id: '11',
        title: 'Veggie Wrap',
        price: 14.00,
        description: 'Grilled vegetables, hummus, spinach, and feta cheese in a spinach tortilla.',
        category: 'Lunch',
        image: require('./Images/Menu/Lunch/Veggie-Wrap.jpg'),

    },
    {
        id: '12',
        title: 'Classic Beef Burger',
        price: 18.00,
        description: 'Classic burger with cheddar, lettuce, tomato, pickles, and house-made sauce on a brioche bun.',
        category: 'Lunch',
        image: require('./Images/Menu/Lunch/Beef-Burger.jpg'),

    },
    {
        id: '13',
        title: 'Veggie Tacos',
        price: 16.00,
        description: 'Taco',
        category: 'Lunch',
        image: require('./Images/Menu/Lunch/Veggie-Taco.jpg'),
    },
    {
        id: '14',
        title: 'Grilled Ribeye Steak',
        price: 34.00,
        description: '300g ribeye, served with garlic mashed potatoes and steamed vegetables.',
        category: 'Dinner',
    },
    {
        id: '15',
        title: 'Pan-Seared Salmon',
        price: 28.00,
        description: 'Served with quinoa, roasted asparagus, and lemon-butter sauce.',
        category: 'Dinner',
    },
    {
        id: '16',
        title: 'Chicken Parmesan',
        price: 22.00,
        description: 'Breaded chicken breast topped with marinara and mozzarella, served with spaghetti.',
        category: 'Dinner',
    },
    {
        id: '17',
        title: 'Lamb Shank',
        price: 30.00,
        description: 'Slow-cooked lamb served with creamy polenta and rosemary jus.',
        category: 'Dinner',
    },
    {
        id: '18',
        title: 'Seafood Linguine',
        price: 26.00,
        description: 'Fresh prawns, mussels, and squid tossed in a garlic white wine sauce with linguine.',
        category: 'Dinner',
    },
    {
        id: '19',
        title: 'Mushroom Risotto',
        price: 22.00,
        description: 'Creamy arborio rice cooked with wild mushrooms, parmesan, and truffle oil.',
        category: 'Dinner',
    },
    {
        id: '20',
        title: 'Grilled Veggie Plate',
        price: 15.00,
        description: 'A variety of grilled seasonal vegetables served with a side of couscous and tzatziki.',
        category: 'Dinner',
    },
    {
        id: '21',
        title: 'Vegan Lentil Bolognese',
        price: 18.00,
        description: 'Lentils in a rich tomato sauce served over spaghetti.',
        category: 'Dinner',
    },
    {
        id: '22',
        title: 'Chocolate Lava Cake',
        price: 10.00,
        description: 'Warm chocolate cake with a gooey center, served with vanilla ice cream.',
        category: 'Dessert',
    },
    {
        id: '23',
        title: 'Vegan Chocolate Lava Cake',
        price: 11.00,
        description: 'Plant-based warm chocolate cake with a gooey center, served with coconut ice cream.',
        category: 'Dessert',
    },
    {
        id: '24',
        title: 'Apple Crumble',
        price: 9.00,
        description: 'Baked apples with cinnamon, topped with a buttery crumble and served with whipped cream.',
        category: 'Dessert',
    },
    {
        id: '25',
        title: 'Tiramisu',
        price: 10.00,
        description: 'Layers of coffee-soaked ladyfingers, mascarpone cream, and cocoa powder.',
        category: 'Dessert',
    },
    {
        id: '26',
        title: 'Ice Cream Sundae',
        price: 8.00,
        description: 'Vanilla ice cream topped with chocolate sauce, whipped cream, and cherries.',
        category: 'Dessert',
    }
];